# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "Len-Li"
repo_name: "cv-arxiv-daily"
show_authors: True
show_links: True
show_badge: False
max_results: 200

publish_readme: True
publish_gitpage: True
publish_wechat: False

# file paths
json_readme_path: './docs/cv-arxiv-daily.json'
json_gitpage_path: './docs/cv-arxiv-daily-web.json'
json_wechat_path: './docs/cv-arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search
keywords:
    "3D":
        filters: ["3D", "NeRF", "neural radiance field", "3D Gaussian Splatting", "3D Reconstruction"]
        categories: ["cat:cs.CV", "cat:cs.GR", "cat:cs.RO"]
    "Diffusion":
        filters: ["GAN", "diffusion", "diffusion model", "controlnet", "controllable generation", "image generation", "video diffusion", "video generation", "Text-to-Video", "text to image"]
    "Industry":
        filters: ["NVIDIA", "Waymo", "DJI", 'Waabi', 'Raquel Urtasun', 'Sanja Fidler']
    "Autonomous Driving":
        filters: ["Autonomous Driving", "Self-driving", "Shenlong Wang", 'Marco Pavone', 'Andreas Geiger', 'Hongyang Li', 'Yikang Li', 'Wei-Chiu Ma', 'Hang Zhao', 'Li Auto']
        categories: ["cat:cs.CV", "cat:cs.GR", "cat:cs.RO"]
    "Traffic Simulation":
        filters: ["Traffic Simulation", "Motion Prediction", "Motion Planning", "Trajectory Prediction"]
        categories: ["cat:cs.CV", "cat:cs.GR", "cat:cs.RO"]

