# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "Len-Li"
repo_name: "cv-arxiv-daily"
show_authors: True
show_links: True
show_badge: False
max_results: 300

publish_readme: True
publish_gitpage: True
publish_wechat: False

# file paths
json_readme_path: './docs/cv-arxiv-daily.json'
json_gitpage_path: './docs/cv-arxiv-daily-web.json'
json_wechat_path: './docs/cv-arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search
keywords:
    "3D": 
        filters: ["3D"]
    # "3D detection": 
    #     filters: ["3D detection", "3D object detection", "BEV detection"]
    "NeRF":
        filters: ["NeRF", "neural radiance field"]
    "Industry":
        filters: ["NVIDIA", "Waymo", "DJI", 'Waabi', 'Raquel Urtasun', 'Sanja Fidler']
    "Autonomous Driving":
        filters: ["Autonomous Driving", "Self-driving", "Shenlong Wang", 'Marco Pavone', 'Andreas Geiger', 'Hongyang Li', 'Yikang Li', 'Wei-Chiu Ma']
    "NeRF + Autonomous Driving":
        filters: ["Autonomous Driving", "Self-driving", "NeRF", "neural radiance field"]
    "Adversarial":
        filters: ["Adversarial", "Robustness"]
    "Traffic Simulation":
        filters: ["Traffic Simulation", "Motion Prediction", "Motion Planning", "Trajectory Prediction"]
